/**
 * POST /trace route handler for the ZAM HTTP Service.
 *
 * Receives a trace JSON object (already produced by a prior /plan call)
 * and returns { explanation: "..." } — a human-readable explanation
 * generated by the pure explainTrace() function.
 *
 * This handler does NOT touch src/core/trace-summary-assembler.ts.
 * Schema validation of the trace body is intentionally lenient here:
 * the trace schema is large and complex (749 lines, 8 required phases).
 * The handler accepts any JSON object and explains what it finds,
 * returning a minimal explanation for partial/empty traces.
 *
 * Canonical: docs/21 §4.2; docs/18 §4.3.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { buildError } from '../errors.js';
import { explainTrace } from '../trace-explainer.js';

/** POST /trace request body shape. */
interface TraceRequestBody {
  trace: unknown;
}

/**
 * Register the POST /trace route on the Fastify instance.
 * Canonical: docs/21 §4.2.
 */
export async function traceRoutes(fastify: FastifyInstance): Promise<void> {
  fastify.post<{ Body: TraceRequestBody }>(
    '/trace',
    async (request: FastifyRequest<{ Body: TraceRequestBody }>, reply: FastifyReply) => {
      const body = request.body;

      if (
        typeof body !== 'object' ||
        body === null ||
        !('trace' in body)
      ) {
        return reply.status(400).send(
          buildError('VALIDATION_ERROR', 'Request body must contain a "trace" field.'),
        );
      }

      const traceValue = body.trace;

      if (typeof traceValue !== 'object' || traceValue === null) {
        return reply.status(400).send(
          buildError('VALIDATION_ERROR', '"trace" must be a non-null JSON object.'),
        );
      }

      const explanation = explainTrace(traceValue);

      return reply.status(200).send({ explanation });
    },
  );
}
